plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - LICENSE.md
  - README.md
#theme: jekyll-theme-hacker
remote_theme: liamg/jekyll-theme-abysm
title: sreiche's published docs
description: A one-man bedroom studio.
